name: Publish

on:
  repository_dispatch:
    types: [update-style-forge]

permissions:
  contents: write

jobs:
  update-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Configure git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Wait for 10 seconds
        run: sleep 10

      - name: Determine version update type
        id: get_update_type
        run: echo "Update type is ${{ github.event.client_payload.update_type }}"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Yarn
        run: |
          yarn install --frozen-lockfile
          yarn upgrade ${{ github.event.client_payload.package_name }} --latest

      - name: Increment version
        run: |
          if [ "${{ github.event.client_payload.update_type }}" == "major" ]; then
            yarn version --major
          elif [ "${{ github.event.client_payload.update_type }}" == "minor" ]; then
            yarn version --minor
          else
            yarn version --patch
          fi

      - name: Build project
        run: yarn build

      - name: Git add
        run: git add package.json yarn.lock style-forge.css

      - name: Commit
        run: |
          git commit -m 'chore: update ${{ github.event.client_payload.package_name }} and increment version'

      - name: Push
        run: git push origin main --tags

      - name: Set up NPM auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update Style-Forge documentation
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.NOTIFY_GITHUB_TOKEN }}" \
            https://api.github.com/repos/Style-Forge/hub/dispatches \
            -d '{"event_type":"update-docs"}'
